export const RM_COLOR_BASE_WHITE = "#ffffff";
export const RM_COLOR_BASE_RED = "#e11900";
export const RM_COLOR_BASE_GREEN = "#048848";
export const RM_COLOR_BASE_ORANGE = "#ff991f";
export const RM_COLOR_BASE_BLACK = "#000000";
export const RM_COLOR_BASE_GRAY_MIDDLE = "#575756";
export const RM_COLOR_BASE_GRAY_LIGHT_20 = "#797978";
export const RM_COLOR_BASE_GRAY_LIGHT_30 = "#898989";
export const RM_COLOR_BASE_GRAY_LIGHT_50 = "#ababaa";
export const RM_COLOR_BASE_GRAY_LIGHT_80 = "#dddddd";
export const RM_COLOR_BASE_GRAY_DARK_20 = "#464645";
export const RM_COLOR_BASE_GRAY_DARK_30 = "#3d3d3c";
export const RM_COLOR_BASE_GRAY_DARK_50 = "#2c2c2b";
export const RM_COLOR_BASE_GRAY_DARK_80 = "#111111";
export const RM_COLOR_BASE_YELLOW_MIDDLE = "#fdc010";
export const RM_COLOR_BASE_YELLOW_LIGHT_20 = "#fdcd40";
export const RM_COLOR_BASE_YELLOW_LIGHT_30 = "#fed358";
export const RM_COLOR_BASE_YELLOW_LIGHT_50 = "#fedf87";
export const RM_COLOR_BASE_YELLOW_LIGHT_80 = "#fff2cf";
export const RM_COLOR_BASE_YELLOW_DARK_20 = "#ca9a0d";
export const RM_COLOR_BASE_YELLOW_DARK_30 = "#b1860b";
export const RM_COLOR_BASE_YELLOW_DARK_50 = "#7f6008";
export const RM_COLOR_BASE_YELLOW_DARK_80 = "#332603";
export const RM_COLOR_BASE_BLUE_MIDDLE = "#276ef1";
export const RM_COLOR_BASE_BLUE_LIGHT_20 = "#528bf4";
export const RM_COLOR_BASE_BLUE_LIGHT_30 = "#6899f5";
export const RM_COLOR_BASE_BLUE_LIGHT_50 = "#93b6f8";
export const RM_COLOR_BASE_BLUE_LIGHT_80 = "#d4e2fc";
export const RM_COLOR_BASE_BLUE_DARK_20 = "#1f58c1";
export const RM_COLOR_BASE_BLUE_DARK_30 = "#1b4da9";
export const RM_COLOR_BASE_BLUE_DARK_50 = "#143779";
export const RM_COLOR_BASE_BLUE_DARK_80 = "#081630";
export const RM_COLOR_BASE_PINK_MIDDLE = "#ff6fff";
export const RM_COLOR_BASE_PURPLE_MIDDLE = "#800080";
export const RM_COLOR_BASE_VIOLET_MIDDLE = "#b93bc2";
export const RM_COLOR_BUTTON_PRIMARY_ENABLED_BACKGROUND = "#575756";
export const RM_COLOR_BUTTON_PRIMARY_ENABLED_FOREGROUND = "#ffffff";
export const RM_COLOR_BUTTON_PRIMARY_HOVERED_BACKGROUND = "#3d3d3c";
export const RM_COLOR_BUTTON_PRIMARY_HOVERED_FOREGROUND = "#ffffff";
export const RM_COLOR_BUTTON_PRIMARY_FOCUSED_BACKGROUND = "#797978";
export const RM_COLOR_BUTTON_PRIMARY_FOCUSED_FOREGROUND = "#ffffff";
export const RM_COLOR_BUTTON_PRIMARY_PRESSED_BACKGROUND = "#111111";
export const RM_COLOR_BUTTON_PRIMARY_PRESSED_FOREGROUND = "#ffffff";
export const RM_COLOR_BUTTON_PRIMARY_DISABLED_BACKGROUND = "#dddddd";
export const RM_COLOR_BUTTON_PRIMARY_DISABLED_FOREGROUND = "#ababaa";
export const RM_COLOR_BUTTON_SECONDARY_ENABLED_BACKGROUND = "#fff2cf";
export const RM_COLOR_BUTTON_SECONDARY_ENABLED_FOREGROUND = "#7f6008";
export const RM_COLOR_BUTTON_SECONDARY_HOVERED_BACKGROUND = "#fedf87";
export const RM_COLOR_BUTTON_SECONDARY_HOVERED_FOREGROUND = "#7f6008";
export const RM_COLOR_BUTTON_SECONDARY_FOCUSED_BACKGROUND = "#fff2cf";
export const RM_COLOR_BUTTON_SECONDARY_FOCUSED_FOREGROUND = "#7f6008";
export const RM_COLOR_BUTTON_SECONDARY_PRESSED_BACKGROUND = "#ca9a0d";
export const RM_COLOR_BUTTON_SECONDARY_PRESSED_FOREGROUND = "#fff2cf";
export const RM_COLOR_BUTTON_SECONDARY_DISABLED_BACKGROUND = "#fff2cf";
export const RM_COLOR_BUTTON_SECONDARY_DISABLED_FOREGROUND = "#fed358";
export const RM_COLOR_FONT_BASE = "#e11900";
export const RM_COLOR_FONT_SECONDARY = "#048848";
export const RM_COLOR_FONT_TERTIARY = "#ababaa";
export const RM_LINE_HEIGHT_FONT_SMALL = 1; // the small line-height of the font
export const RM_LINE_HEIGHT_FONT_MEDIUM = 1.25; // the medium line-height of the font
export const RM_LINE_HEIGHT_FONT_LARGE = 1.5; // the large line-height of the font
export const RM_LINE_HEIGHT_FONT_BASE = 1.25; // the base line-height of the font
export const RM_LINE_HEIGHT_FONT_DISPLAY_SMALL = 2.75; // the small line-height of the font
export const RM_LINE_HEIGHT_FONT_DISPLAY_MEDIUM = 3.25; // the medium line-height of the font
export const RM_LINE_HEIGHT_FONT_DISPLAY_LARGE = 4; // the large line-height of the font
export const RM_LINE_HEIGHT_FONT_HEADLINE_SMALL = 1.5; // the small line-height of the font
export const RM_LINE_HEIGHT_FONT_HEADLINE_MEDIUM = 2.25; // the medium line-height of the font
export const RM_LINE_HEIGHT_FONT_HEADLINE_LARGE = 2.5; // the large line-height of the font
export const RM_LINE_HEIGHT_FONT_TITLE_SMALL = 1.25; // the small line-height of the font
export const RM_LINE_HEIGHT_FONT_TITLE_MEDIUM = 1.5; // the medium line-height of the font
export const RM_LINE_HEIGHT_FONT_TITLE_LARGE = 1.75; // the large line-height of the font
export const RM_LINE_HEIGHT_FONT_LABEL_SMALL = 1; // the small line-height of the font
export const RM_LINE_HEIGHT_FONT_LABEL_MEDIUM = 1; // the medium line-height of the font
export const RM_LINE_HEIGHT_FONT_LABEL_LARGE = 1.25; // the large line-height of the font
export const RM_LINE_HEIGHT_FONT_BODY_SMALL = 1; // the small line-height of the font
export const RM_LINE_HEIGHT_FONT_BODY_MEDIUM = 1.25; // the medium line-height of the font
export const RM_LINE_HEIGHT_FONT_BODY_LARGE = 1.5; // the large line-height of the font
export const RM_SIZE_FONT_SMALL = "0.75rem"; // the small size of the font
export const RM_SIZE_FONT_MEDIUM = "1rem"; // the medium size of the font
export const RM_SIZE_FONT_LARGE = "2rem"; // the large size of the font
export const RM_SIZE_FONT_BASE = "1rem"; // the base size of the font
export const RM_SIZE_FONT_DISPLAY_SMALL = "2.25rem"; // the small size of the font
export const RM_SIZE_FONT_DISPLAY_MEDIUM = "2.75rem"; // the medium size of the font
export const RM_SIZE_FONT_DISPLAY_LARGE = "3.5rem"; // the large size of the font
export const RM_SIZE_FONT_HEADLINE_SMALL = "1.5rem"; // the small size of the font
export const RM_SIZE_FONT_HEADLINE_MEDIUM = "1.75rem"; // the medium size of the font
export const RM_SIZE_FONT_HEADLINE_LARGE = "2rem"; // the large size of the font
export const RM_SIZE_FONT_TITLE_SMALL = "0.875rem"; // the small size of the font
export const RM_SIZE_FONT_TITLE_MEDIUM = "1rem"; // the medium size of the font
export const RM_SIZE_FONT_TITLE_LARGE = "1.375rem"; // the large size of the font
export const RM_SIZE_FONT_LABEL_SMALL = "0.75rem"; // the small size of the font
export const RM_SIZE_FONT_LABEL_MEDIUM = "0.875rem"; // the medium size of the font
export const RM_SIZE_FONT_LABEL_LARGE = "1rem"; // the large size of the font
export const RM_SIZE_FONT_BODY_SMALL = "0.75rem"; // the small size of the font
export const RM_SIZE_FONT_BODY_MEDIUM = "0.875rem"; // the medium size of the font
export const RM_SIZE_FONT_BODY_LARGE = "1rem"; // the large size of the font
export const RM_TYPOGRAPHY_FONT_FAMILY_SANS =
    "-apple-system, BlinkMacSystemFont, 'Noto Sans', Roboto, sans-serif";
export const RM_TYPOGRAPHY_FONT_FAMILY_MONO =
    "ui-monospace, 'Noto Sans Mono', 'Roboto Mono', monospace";
export const RM_WEIGHT_FONT_BOLD = "600";
export const RM_WEIGHT_FONT_MEDIUM = "500";
export const RM_WEIGHT_FONT_REGULAR = "400";
export const RM_ZINDEX_DROPDOWN = 1000; // Dropdown layer position
export const RM_ZINDEX_STICKY = 1020; // Sticky layer position
export const RM_ZINDEX_FIXED = 1030; // Fixed layer position
export const RM_ZINDEX_OFFCANVAS_BACKDROP = 1040; // Off-canvas backdrop layer position
export const RM_ZINDEX_OFFCANVAS = 1045; // Off-canvas, drawer, flyout or side panel layer position
export const RM_ZINDEX_MODAL_BACKDROP = 1050; // Modal backdrop layer position
export const RM_ZINDEX_MODAL = 1055; // Modal, dialogues, notifications layer position
export const RM_ZINDEX_POPOVER = 1070; // Popover layer position
export const RM_ZINDEX_TOOLTIP = 1080; // Tooltip layer position
export const RM_ZINDEX_TOAST = 1090; // Toast layer position
